### PR TITLE
Conversion from NSURLConnection to NSURLSession

### PR DESCRIPTION
**Pull request by meteochu**
Finished #119 

Disclaimer, I've only tested with the Demo App, which uses only simple .GET and .POST requests. 
Someone should probably test out Streaming and Media (Data) Uploads before merging this.

### CODE REVIEW

**Comment by zntfdr** [comment]
This is amazing! Thanks a million for this :clap: :clap: 

I'll test the streaming enpoints this evening (9am here).

@mattdonnelly please add @meteochu to the repo collaborators: he's way more worthy than me. 
I don't mind if you even remove me from the collaborators list: I can still participate like I did in the past, what matters is that @meteochu becomes a collaborator :smile:

**Comment by mattdonnelly** [comment]
Haha, good call. I'll add him as one now :smile:

**Comment by mattdonnelly** [comment]
Also @meteochu, thank you for all the work you've been putting in, this looks great! . I can try testing it with the streaming and media APIs this evening.

**Comment by zntfdr** [comment]
Thank you @mattdonnelly , I'm glad to hear that! (both the testing and Andy addition among the collaborators :+1: )

**Comment by mattdonnelly** [comment]
Streaming doesn't seem to work. Returns the following error:
```NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
An SSL error has occurred and a secure connection to the server cannot be made.```

**Comment by mattdonnelly** [comment]
Never mind, just had to enable NSAllowsArbitraryLoads and it worked :+1:

**Comment by mattdonnelly** [comment]
Never mind, enabled NSAllowsArbitraryLoads and it works now :+1:

**Comment by mattdonnelly** [comment]
And media uploads worked too! I'm happy to merge this in now. Nice one @meteochu, thanks for the contribution :100:

**Comment by zntfdr** [comment]
Thanks @meteochu! :clap:

**Pull request merged**
