### PR TITLE
Remove CommonCrypto

### PR DESCRIPTION
**Pull request by Allezxandre**
CommonCrypto is source of many issues. For instance, it makes CocoaPods a no-go. Now this will be fixed for good!

Most of the modifications are code from [this commit on OAuthSwift](https://github.com/OAuthSwift/OAuthSwift/commit/5d6f60d749fe25312196c4aab7bd05973f666893)

Also added SwifterReverseAuth by @Gurpartap: [Swifter-Reverse-Auth](https://github.com/Gurpartap/Swifter-Reverse-Auth)

### CODE REVIEW

**Comment by Allezxandre** [comment]
Hum... It looks like I'm having some XREF issues with Xcode...

**Comment by Allezxandre** [comment]
It's working now, and I can successfully compile another project with Swifter as a dependency. No more X-REF issues.

**Comment by meteochu** [comment]
Your commits have more than what's necessary as part of the titled Pull Request, so it will not be merged. Either clear the commits unrelated to removing CommonCrypto as a dependency, or I can have a go at implementing it when I get time.

**Comment by meteochu** [comment]
I've added the files from this pull request to the [swift-3](/mattdonnelly/Swifter/tree/swift-3) branch. This pull request will now be closed.

Thank you.

**Pull request closed without merging**
