### PR TITLE
Add support for getting raw and/or decoded data via Decodable protocol

### PR DESCRIPTION
**Pull request by zachrwolfe**
As mentioned in #203, I found my previous solution to this problem #196 had a few issues in practice. I also would prefer not to have to maintain an independent fork if I don't have to. So I decided to take another go at it, and the solution I came up with this time is more flexible, much simpler and more ergonomic than the old one. It's also slightly different from what I proposed in the above issue.

At the core of this pull request is a new type, `RawSuccessHandler`, which wraps a simple closure. A single parameter of this type is added to each endpoint method. The user can initialize it with one of three static methods to get either just the raw data, the raw data and a decoded value, or just a decoded value respectively--alternative name suggestions welcome:
- `public static func data(handler: @escaping (Data) -> Void) -> RawSuccessHandler`
- `public static func dataAndDecoding<Entity: Decodable>(_ type: Entity.Type, handler: @escaping (Data, Entity?) -> Void) -> RawSuccessHandler`
- `public static func decoding<Entity: Decodable>(_ type: Entity.Type, handler: @escaping (Entity) -> Void) -> RawSuccessHandler`

Behind the scenes, the closure wrapped by `RawSuccessHandler` itself accepts a `Swifter.FailureHandler`, which `jsonRequest()` takes advantage of to propagate decoding errors to the user-provided failure handler.

Below are some code samples.

Prints the home timeline in JSON form:
```
swifter.getHomeTimeline(
    rawSuccess: .data { data in
        print(String(data: data, encoding: .utf8)!)
    }
)
```

Prints the home timeline in JSON form, prints a belittling message, then prints a decoding error:
```
swifter.getHomeTimeline(
    rawSuccess: .dataAndDecoding(Int.self) { data, timeline in
        print(String(data: data, encoding: .utf8)!)
        print(timeline ?? "The home timeline isn't an integer, dummy!")
    },
    failure: { error in print(error) }
)
```

Prints the text of each tweet in the home timeline:
```
struct Tweet: Decodable {
    let text: String
}
swifter.getHomeTimeline(
    rawSuccess: .decoding([Tweet].self) { tweets in
        for tweet in tweets {
            print(tweet.text)
        }
    }
)
```

### CODE REVIEW

**Comment by buddax2** [comment]
any chance to fix the conflicts and merge this PR?

**Comment by meteochu** [comment]
Hi, thanks for taking another attempt at this. 

First of all, I would argue that if we're adding a `rawSuccess` handler, we might as well redo the entire successHandler to handle the different possible SuccessHandlers, which include our current `JSON`, raw `Data`, and `Decodable`. It seems redundant to have 2 separate places to do decoding. 

Second of all, since this _will_ be breaking change, it's best that we go through and look at the different methods of doing this most efficiently. That said, since it's basically guaranteed to be breaking change, we should also add a migration option and deprecate the older methods.

Third of all, there're too many conflicts right now, can you please fix those?

**Comment by zachrwolfe** [comment]
Thanks Andy, I’m glad this is more to your liking. I actually agree re: just replacing success handler, but I wanted to err on the side of source compatibility. One consideration with that is the case of streaming APIs, which IIRC split their output into stall warning handlers and progress handlers. Not sure how to handle that yet. Will look into this soon if not tonight.

Also, how do you feel about—if we’re going to be breaking code anyway—instead of adding another method to what is now called RawSuccessHandler for getting a JSON value, we just replace the manual parsing logic in JSON with my implementation of Decodable conformance? That way it wouldn’t be a special case, the user could just choose to call .decoding(JSON.self).

I’ll fix up the merge conflicts soon too.

**Comment by zachrwolfe** [comment]
After looking into this, here's where I come down on the outlier cases Swifter currently handles.

- `CursorSuccessHandler`: This should be removed entirely and replaced with a normal `RawSuccessHandler`.

- Search success handler: Likewise, I feel this should be scrapped.

- Stall warning & progress handlers: I'd be fine with just going with a single progress handler and being done with it like the others. However I think in this case there might actually be some value in making this distinction at the library level since you're dealing with one of two very distinct cases. Have a look at my [draft implementation](https://github.com/zachrwolfe/Swifter/commit/87a8625f9e22f2a5adb1a738009db91cd01da049) when you get the chance. Hasn't been tested on the API but decoding sample data works.

**Comment by zachrwolfe** [comment]
Fixed the conflicts, though clearly not ready for merge yet.

**Comment by zachrwolfe** [comment]
Since opening this pull request and having a chance to contemplate what abandoning the goal of source compatibility might look like, I’ve come up with the idea for an even simpler solution to this problem.

I propose adding a lightweight `Result` type to the project. Something along the lines of the following (implementations removed because they are trivial):

```swift
public enum Result<Wrapped> {
    case success(Wrapped)
    case failure(Error)

    public func unwrap() throws -> Wrapped
    public func map<T>(_ transform: (Wrapped) throws -> T) -> Result<T>
}
```

To improve ergonomics when decoding data, an extension on `Result` where `Wrapped == Data` could be added with a method `func decoding<T: Decodable>(_ type: T.Type) -> Result<T>`, implemented as a call to `map` that calls `Swifter.decoder.decode()`.

All endpoints could simply take a single completion/progress closure which accepts a `Result<Data>` in place of the status quo success/failure handlers. This would also allow users to take advantage of trailing closure syntax, something they can’t  now due to the split success/failure handler arguments.

Compared to my previous solution, this is relatively simple to implement, provides maximum flexibility to the user without bloating the library with a bunch of permutations of different options the user can respond to. In the simple case of decoding a value of JSON type, the user will need to write a tiny bit more code, but I think the added flexibility for the more complex cases and reduced implementation complexity are worth it. As an aside, when future language concurrency features like async-await finally land, this solution should provide a pretty trivial migration path for user code to that paradigm.

@meteochu @zntfdr Do you agree that this is an improvement? Do you see any potential issues with this approach?

**Comment by enricenrich** [comment]
Jumping into this conversation as I started to use this library.

One thing that I would like to bring to the discussion is to have in mind the use of the `JSON` class name. Some of us (like me) probably use SwiftyJSON in other places of our code to properly handle JSON. It would be great to rename the `JSON` class on Swifter to `SwifterJSON` for example so it doesn't have any conflict with SwiftJSON.

**Comment by zachrwolfe** [comment]
Seems reasonable to me, @enricenrich! Probably deserves to be its own pull request, though.

**Comment by enricenrich** [comment]
@zachrwolfe Agree that it probably deserves its own PR. This said, I think that the PR for the `JSON` class and this one should be related and be merged together 🙂

**Comment by zachrwolfe** [comment]
@meteochu @zntfdr Friendly bump now that the holidays are through and people are probably starting to settle down. :)

To TL;DR and expand on my previous post a bit, I’d like to take a step back and do the following:
- Add a small generic `Result` type to the library with `map` and `flatMap` methods that work like those on `Optional`, possibly with additional methods to make decoding easier when `Wrapped` == `Data`
- Add Codable conformance to the `JSON` enum to make it just “another type” that could be decoded in the same way a custom type would be. Remove the equivalent encoding/decoding methods that would be made redundant by this.
- Consolidate all success, progress, and failure handlers into unified response or completion handlers which accept a `Result<Data>`.
- Implicit in the above is the removal of all instances of parsing out data from the API that currently exist in the library. Examples off the top of my head are parsing out cursors for `CursorSuccessHandler` as well as separating progress responses from stall warning responses in the streaming API.

I’d be happy to implement this as soon as possible, but I want to be sure there is some consensus on this approach first. Please let me know what you think as soon as it’s convenient!

**Comment by zachrwolfe** [comment]
Note that on the last bullet point, it should be possible to replicate the same behaviour pretty easily through the creation of a couple generic `Decodable` types, but personally I think we should take this opportunity to push the library more consistently in the direction of “basic wrapper for getting and manipulating data from Twitter”, rather than keeping things around for legacy reasons. Again though, I value your input!

**Comment by zeusent** [comment]
Hey @zachrwolfe I know it's been a while but I was curious what was the end of this. I find this framework super nice but the fact that it uses this `JSON` enum si a "no-no" for me. I would have really liked it if it would just hand me the raw data responses and leave the parsing to me.

**Comment by zachrwolfe** [comment]
Cliff notes: The maintainers stopped responding my issue & PR. I then--no longer concerned about the prospects of getting my changes into master--proceeded to go crazy, experimenting with all sorts of different approaches for exposing custom decoding schemes in a flexible and ergonomic way. I then got annoyed at how difficult it was to experiment because there was so much boilerplate. So I designed and implemented a domain specific language for generating Swifter methods from a specification of the Twitter API. Then I realized the project I was using the Twitter API for was a bad idea in the first place and abandoned it. 🤦

I had fun tho.

If you want to take a look at my fork, I've just made it public here: https://gitlab.com/zachrwolfe/Swifter

Notes:
- The DSL transpiler is in /Preprocessor. It uses a hardcoded path, which you'd have to change if you wanted to actually use it.
- It uses a hand-rolled `Promise` type instead of success and error handlers, which you would use like so:
```swift
swifterInstance.getHomeTimeline(
    count: 200,
    sinceID: sinceID,
    maxID: maxID,
    trimUser: false,
    contributorDetails: false,
    includeEntities: true,
    tweetMode: .extended
).decode([Tweet].self)
    .then { tweets in ... }
    .catch { error in ... }
    .start()
```

**Comment by meteochu** [comment]
I'm sorry to hear that is how you felt when we discussed the PR in the past. I actually did not even realize that I stopped responding to this, but I had since then become busy from the jobs I was having at the time and was not really able to maintain Swifter. 

That being said, I'm open to start a new discussion around this because I do think this is absolutely a topic we should discuss (if you are still willing) to see what the best API design for this is without duplicating the code and possibly without breaking existing API.

**Comment by smhk** [comment]
Swifter is AMAZING.

Let's just keep it as simple as possible with the limited and generous time available.

**Comment by meteochu** [comment]
Starting a new discussion in #283.

**Comment by zachrwolfe** [comment]
No worries, @meteochu! I understood that you must have been quite quite busy. The write-up in your issue looks like a great starting point. I don't think I'll have time to implement this, but I'm happy to discuss.

**Pull request closed without merging**
