### PR TITLE
Support media/upload #62

### PR DESCRIPTION
**Pull request by s-aska**
corresponding to the plurality of image upload.

https://dev.twitter.com/rest/public/uploading-media

### CODE REVIEW

**Comment by alexdd55** [comment]
changes delivers a linker error message for me?

**Comment by s-aska** [comment]
Do you fail to build?
The linker error I have not received.

**Comment by alexdd55** [comment]
Yes. i revert the changes and didn’t copy the error message, sorry.
But i think its a 32/64 bit CPU compile thing

**Comment by s-aska** [comment]
I tried various.
But it does not really reproduce :/
Please try to clean.

**Comment by alexdd55** [comment]
i will try again and let you know. :+1:

**Pull request closed without merging**
